"""Add Module C - The Proxy tables

Revision ID: 468f79c406f7
Revises: f92b648bc96a
Create Date: 2026-02-04 12:32:02.936946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468f79c406f7'
down_revision: Union[str, Sequence[str], None] = 'f92b648bc96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_poas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('specific_services', sa.JSON(), nullable=True),
    sa.Column('spend_limit', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_poas_agent_id'), 'smart_poas', ['agent_id'], unique=False)
    op.create_index(op.f('ix_smart_poas_id'), 'smart_poas', ['id'], unique=False)
    op.create_index(op.f('ix_smart_poas_senior_id'), 'smart_poas', ['senior_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poa_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('request_details', sa.JSON(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=True),
    sa.Column('advocate_notified', sa.Boolean(), nullable=True),
    sa.Column('advocate_notification_time', sa.DateTime(), nullable=True),
    sa.Column('override_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['poa_id'], ['smart_poas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('credential_presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poa_id', sa.Integer(), nullable=False),
    sa.Column('presented_to', sa.String(length=200), nullable=False),
    sa.Column('presentation_method', sa.String(length=50), nullable=False),
    sa.Column('presented_at', sa.DateTime(), nullable=True),
    sa.Column('verification_code', sa.String(length=100), nullable=True),
    sa.Column('verified_by_recipient', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('document_hash', sa.String(length=256), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['poa_id'], ['smart_poas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_presentations_id'), 'credential_presentations', ['id'], unique=False)
    op.create_table('encrypted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poa_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poa_id'], ['smart_poas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_tokens_id'), 'encrypted_tokens', ['id'], unique=False)
    op.create_table('break_glass_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=100), nullable=False),
    sa.Column('trigger_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('advocate_id', sa.String(length=100), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('two_fa_code', sa.String(length=10), nullable=True),
    sa.Column('two_fa_sent_at', sa.DateTime(), nullable=True),
    sa.Column('two_fa_verified_at', sa.DateTime(), nullable=True),
    sa.Column('liveness_required', sa.Boolean(), nullable=True),
    sa.Column('liveness_verified', sa.Boolean(), nullable=True),
    sa.Column('liveness_verified_at', sa.DateTime(), nullable=True),
    sa.Column('liveness_data', sa.JSON(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('denied_at', sa.DateTime(), nullable=True),
    sa.Column('denied_by', sa.String(length=100), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_log_id')
    )
    op.create_index(op.f('ix_break_glass_events_id'), 'break_glass_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_break_glass_events_id'), table_name='break_glass_events')
    op.drop_table('break_glass_events')
    op.drop_index(op.f('ix_encrypted_tokens_id'), table_name='encrypted_tokens')
    op.drop_table('encrypted_tokens')
    op.drop_index(op.f('ix_credential_presentations_id'), table_name='credential_presentations')
    op.drop_table('credential_presentations')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_smart_poas_senior_id'), table_name='smart_poas')
    op.drop_index(op.f('ix_smart_poas_id'), table_name='smart_poas')
    op.drop_index(op.f('ix_smart_poas_agent_id'), table_name='smart_poas')
    op.drop_table('smart_poas')
    # ### end Alembic commands ###
